feat: add DARTSClassifier
AutoResearch/autora pull request #164
Opened 2022-12-06 19:48 UTC by hollandjg

## Description

Add a new wrapper `DARTSClassifier` to do classification using DARTS.

resolves #108 

### Type of change:
- New feature (non-breaking change which adds functionality)

2022-12-13 19:26 UTC, benwandrew requested changes

2022-12-13 19:26 UTC, benwandrew commented on autora/skl/darts.py
> +            but can be set to a graph based on a sample on the edge weights
```suggestion
            but can be set to a graph based on a sample of the edge weights
```

2022-12-13 19:26 UTC, benwandrew commented on autora/skl/darts.py
> +            param_updates_per_epoch: Number of updates to perform per epoch.
```suggestion
            param_updates_per_epoch: Number of updates to perform per epoch
```

2022-12-15 18:07 UTC, hollandjg commented on autora/skl/darts.py
> +    def predict_proba(self, X: np.ndarray) -> np.ndarray:
That's a scikit-learn naming convention. No idea why they chose it.

2023-01-19 15:00 UTC, closed without merging