feature(controller): 4 - put together the components for the upgraded AER Controller
AutoResearch/autora pull request #305
Opened 2023-03-22 21:33 UTC by hollandjg

## Description

Create new `Controller`s which supersede the `SimpleCycle`. 

This is part of the solution to:
- #238 
- #247 
- #248

This builds on:
- #299 
- #303
- #304

- resolves #233

Todos:
- [ ] Convert `__init__.py` into a notebook and include in documentation. Can we still use it as doctests?

### Type of change:
- New feature (non-breaking change which adds functionality)

### Features: 
- **Added a `BaseController`** (`base.py`)
   Handles shared logic (how to get the next step in the cycle, for instance) for all the controller classes
- **Added a `Cycle`**, derived from the `BaseController` (`cycle.py`)
   Has the same interface as the `SimpleCycle` but uses the `Snapshot` state from #299, the `full_cycle_planner` from #303, and the `default_online_executor_collection` from #304 
- **Added a `Controller`**, derived from the `BaseController` (`controller.py`), 
   Offers easier seeding and a history function than the `Cycle`, and the ability to choose a different `planner` function. It uses the `Hitory` state from #299, the `last_result_kind_planner` (as a default) from #303, and the `default_online_executor_collection` from #304. 
   Resolves #233
- **Added documentation** showing all the classes in use (`__init__.py`): 
  - simple execution using the `Cycle`, 
  - more complex execution and customization using the `Controller` and 
  - full customization and multiple experimentalists by using the `BaseController`

2023-03-23 10:52 UTC, musslick commented on autora/controller/__init__.py
> +    ...     )
This is neat!

2023-03-23 11:18 UTC, musslick requested changes
I think this looks fantastic. Especially the ability to define your own planner and introduce contingencies about which experimentalist/theorist to use dependent on the history object. 

The examples in the init are really well documented and this makes we wonder whether we could supply a python notebook here that we could easily integrate in the documentation (or on Google Collab)? I think this would help users a lot. We could literally use the __init__.py examples as the notebook. What do you think?

2023-03-23 11:18 UTC, musslick commented on autora/controller/__init__.py
> +    >>> controller_with_seed_observation = Controller(
Love it!

2023-03-24 15:24 UTC, hollandjg commented
> I think this looks fantastic. Especially the ability to define your own planner and introduce contingencies about which experimentalist/theorist to use dependent on the history object.
> 
> The examples in the init are really well documented and this makes we wonder whether we could supply a python notebook here that we could easily integrate in the documentation (or on Google Collab)? I think this would help users a lot. We could literally use the **init**.py examples as the notebook. What do you think?

Yes, we totally should. I'm not yet sure the best way to do that and integrate the notebook with the documentation though.

2023-04-20 13:22 UTC, hollandjg commented
this is too big. Closing for now, will move this to a separate repo. Thanks for the feedback!

2023-04-20 13:22 UTC, closed without merging