refactor: replace legacy 'numpy.random' function with objects from Random Generator class
AutoResearch/autora pull request #327
Opened 2023-03-28 20:37 UTC by benwandrew

# Description

In various places, our theorists were relying upon the legacy `numpy.random{...}` function. This PR replaces instances of that legacy function with objects from the new Random Generator class.

- resolves #326 

# Type of change

- **refactor**: A code change that neither fixes a bug nor adds a feature

# Features (Optional)
- all legacy `numpy.random{...}` functions replaced with random generator objects

# Questions (Optional)
- Should the generator object — `rng=np.random.default_rng()` — always be passed as an argument, as opposed to initialized and used merely within the body of code?

# Remarks (Optional)
- I tried to grab all instances, which were spread across DARTS, BMS, and BSR to varying degrees.

2023-03-28 22:03 UTC, hollandjg commented
Hey @benwandrew , that was fast! Definitely the fastest issue-based PR I've seen in a long time ;)

> * Should the generator object — `rng=np.random.default_rng()` — always be passed as an argument, as opposed to initialized and used merely within the body of code?

Quoting NEP 19 here (**emphasis** mine): https://albertcthomas.github.io/good-practices-random-number-generators/
> The implicit global RandomState behind the np.random.* convenience functions can cause problems, especially when threads or other forms of concurrency are involved. Global state is always problematic. We categorically recommend avoiding using the convenience functions when reproducibility is involved. […] **The preferred best practice for getting reproducible pseudorandom numbers is to instantiate a generator object with a seed and pass it around.**

I think we might want to go one step further than you have here, and instantiate the RNG in the DARTSRegressor, BMSRegressor and BSRRegressor objects (e.g. make the RNG instantiation an optional argument to the `__init__` function of each of those) and then pass _that_ RNG to each of the functions you've already touched in this PR.

And thinking further, there are places where we use the python standard library random number generator as well, which has the same problems as the numpy.random convenience functions. Perhaps we should do the same thing for that? Quoting https://docs.python.org/3/library/random.html
> The functions supplied by this module are actually bound methods of a hidden instance of the [random.Random](https://docs.python.org/3/library/random.html#random.Random) class. You can instantiate your own instances of [Random](https://docs.python.org/3/library/random.html#random.Random) to get generators that don’t share state.

Thoughts? Perhaps that should be a separate PR?

2023-03-29 17:19 UTC, benwandrew commented
thanks, @hollandjg. that makes good sense (at least at a high level to me -- we'll see about carrying out the details!), including separating out the second bit. 

quick question: what type is appropriate to specify for the RNG in the regressor classes? I tried `Any` from `typing` thinking that we need something compatible with various (`rng.integers`, `rng.uniform`, etc), but keep running into `error: Cannot determine type of "rng"` issues. or am i more generally confused?

2023-03-29 18:49 UTC, hollandjg commented
> quick question: what type is appropriate to specify for the RNG in the regressor classes? I tried `Any` from `typing` thinking that we need something compatible with various (`rng.integers`, `rng.uniform`, etc), but keep running into `error: Cannot determine type of "rng"` issues. or am i more generally confused?

For numpy I think it will be a [`numpy.random.Generator`](https://numpy.org/doc/stable/reference/random/generator.html)
(For the python standard library, when we get there, I think it will be a [`random.Random`](https://docs.python.org/3/library/random.html#random.Random))

2023-03-31 15:52 UTC, hollandjg commented
Hold the press! @musslick would like to contribute to [SRBench](https://cavalab.org/srbench/contributing/), and for that we'll need to provide a `random_state` attribute which we can set on the estimator. The type will be some integer. 
- I think we should consider using that naming convention, and
- we should probably add an option to pass either an integer seed or a full RNG object (whatever type is required for the particular regressor) to the regressor
Thoughts?

2023-03-31 15:55 UTC, hollandjg requested changes
Looks like a good start, couple of change requests to make sure it's easy to seed all the regressors.

2023-06-02 15:11 UTC, hollandjg commented
this needs to be closed here and moved over to the new format!

2023-06-02 15:11 UTC, closed without merging