Docs add tutorials
AutoResearch/autora pull request #429
Opened 2023-06-03 15:35 UTC by younesStrittmatter

# Description

add the tutorials after the introduction

# Remarks (Optional)
This works, but since mkdocs doesn't seem to support having the same file (or import) at two different nav endpoints, a workaround is to import the falsification sampler twice

2023-06-03 18:14 UTC, benwandrew requested changes
also, the tutorials are not launching in Colab. it looks like a path issue somewhere, but i can't seem to resolve

<img width="529" alt="Screen Shot 2023-06-03 at 14 00 18" src="https://github.com/AutoResearch/autora/assets/28738595/cfc38d88-f475-4ddc-a428-7c04c9718615">

2023-06-03 18:23 UTC, younesStrittmatter commented
I kind of think (and am reasonable confident) that the collab tutorials work as soon as the new documentation has been build. (The paths seems right to me, but they don't exist yet on gh-pages since the page have not yet been build)

2023-06-03 18:25 UTC, younesStrittmatter commented on mkdocs.yml
>  - Introduction: 'index.md'
this one no, since it is a own nav page called introduction

2023-06-03 18:49 UTC, benwandrew commented
> I kind of think (and am reasonable confident) that the collab tutorials work as soon as the new documentation has been build. (The paths seems right to me, but they don't exist yet on gh-pages since the page have not yet been build)

ok, sounds good. i just saw that the colab urls for the working ones (eg Basic Usage for model disagreement sampler) matched the nav structure and naming exactly, whereas the url for the ‘Automated Theorist’ under ‘Tutorials’ just has the named bms-tutorial in it. anyway, my confusion, good to approve.

2023-06-03 18:51 UTC, benwandrew approved these changes

2023-06-07 20:54 UTC, hollandjg approved these changes
Looks good to me! 

We might want to add a summary page for the tutorials, and possibly expand them later, so they aren't exactly the same as the originals.

We should also add the `!pip install autora[with-the-right-options]` to the original notebooks – that slipped through the net.

2023-06-07 21:09 UTC, merged