Doc/restructuring general tutorial
AutoResearch/autora pull request #514
Opened 2023-07-05 15:15 UTC by chadcwilliams

# Description

Restructured the main introductory tutorial by splitting it into four notebooks for easier consumption. I have also edited the notebooks. 

*If the issue is on Github, simply link to it using the '#' symbol; otherwise, provide a notion page link)*:
- resolves #510

# Type of change
- **refactor**: A code change that neither fixes a bug nor adds a feature
- **docs**: Documentation only changes

# Remarks (Optional)
- In each notebook, there are links to each other notebook. I'll need to check the links to make sure they are good.

2023-07-05 20:48 UTC, younesStrittmatter commented on mkdocs.yml
> +    -I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'
- I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'

2023-07-05 21:41 UTC, younesStrittmatter commented on docs/tutorials/basic/Tutorial-I-Components.ipynb
> +    {
d

2023-07-05 21:56 UTC, younesStrittmatter commented on mkdocs.yml
> +    -IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```
    - I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'
    - II - Loop Constructs: 'tutorials/basic/Tutorial-II-Loop-Constructs.ipynb'
    - III - Workflow Logic: 'tutorials/basic/Tutorial-III-Workflow-Logic.ipynb'
    - IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```

2023-07-05 21:57 UTC, younesStrittmatter commented on mkdocs.yml
> +    -IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```markdown
    - I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'
    - II - Loop Constructs: 'tutorials/basic/Tutorial-II-Loop-Constructs.ipynb'
    - III - Workflow Logic: 'tutorials/basic/Tutorial-III-Workflow-Logic.ipynb'
    - IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```

2023-07-05 21:58 UTC, younesStrittmatter commented on mkdocs.yml
> +    -IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```    
- I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'
```

2023-07-05 21:59 UTC, younesStrittmatter commented on mkdocs.yml
> +    -IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```suggestion
    - I - Components: 'tutorials/basic/Tutorial-I-Components.ipynb'
    - II - Loop Constructs: 'tutorials/basic/Tutorial-II-Loop-Constructs.ipynb'
    - III - Workflow Logic: 'tutorials/basic/Tutorial-III-Workflow-Logic.ipynb'
    - IV - Customization: 'tutorials/basic/Tutorial-IV-Customization.ipynb'
```

2023-07-05 22:01 UTC, younesStrittmatter requested changes
building of website fails. This should fix it

2023-07-06 12:10 UTC, musslick approved these changes
Looks great, thanks for the restructuring!

2023-07-09 13:22 UTC, younesStrittmatter approved these changes
looks good

2023-07-10 15:42 UTC, hollandjg approved these changes
Looks great!

2023-09-01 20:34 UTC, chadcwilliams commented
Re-implemented with the latest AutoRA versions. However, the latest AutoRA is not yet stable, so this will need to be updated again once AutoRA is stable.

2023-09-05 16:48 UTC, merged