docs: update license to MIT
AutoResearch/autora pull request #537
Opened 2023-08-01 15:20 UTC by benwandrew

# Description

resolves #533 

# Type of change

- **docs**: Documentation only changes

# Questions (Optional)
- would this actually be categorized as a `docs` change (in which case, title of PR and the branch should be different)? wasn't sure which type was best...
- when I selected MIT within "[Choose a license template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#:~:text=Under%20the%20file%20name%2C%20click%20Choose%20a%20license%20template.)", it defaulted to a file name without the `.md` suffix; does this matter? seems like either is [permissible](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#:~:text=In%20the%20file%20name%20field%2C%20type%20LICENSE%20or%20LICENSE.md%20(with%20all%20caps).)?

# Remarks (Optional)
- I will create a new release once this is approved and merged.

2023-08-01 18:34 UTC, hollandjg requested changes
Hi Ben, thanks for this! I think the license file name needs updating in the pyproject.toml file too.

2023-08-05 04:10 UTC, younesStrittmatter approved these changes

2023-08-05 09:07 UTC, benwandrew commented
> Hi Ben, thanks for this! I think the license file name needs updating in the pyproject.toml file too.

@hollandjg guess this needs your approval to merge?

2023-08-05 11:10 UTC, hollandjg approved these changes

2023-08-05 11:11 UTC, merged