doc: added citation info
AutoResearch/autora pull request #580
Opened 2023-11-25 21:48 UTC by musslick

# Description

Added citation info according to GitHub conventions. Note: currently the citation info only lists "official" code maintainers. We will discuss the list once we submit the corresponding article.

2023-11-26 12:15 UTC, benwandrew approved these changes
👍

2023-11-28 16:23 UTC, hollandjg requested changes
One change – please include my ORCID!

2023-11-28 16:23 UTC, hollandjg commented on CITATION.cff
> +  given-names: "John"
```suggestion
- family-names: "Holland"
  given-names: "John"
  orcid: "https://orcid.org/0000-0001-6845-8657"
```

2023-11-30 20:56 UTC, hollandjg approved these changes
Looks good to me!

2023-12-06 14:04 UTC, merged